index:
  path: /
  controller: App\Controller\HomeController::index

login:
  path: /login
  controller: App\Controller\LoginController::index

register:
  path: /register
  controller: App\Controller\RegisterController::index

contact:
  path: /contact
  controller: App\Controller\ContactController::index

api_login:
  path: /api/login
  controller: App\Controller\Api\ApiLoginController::index

api_register:
  path: /api/register
  controller: App\Controller\Api\ApiRegisterController::index
