index:
  path: /
  controller: App\Controller\HomeController::index

login:
  path: /login
  controller: App\Controller\LoginController::index

register:
  path: /register
  controller: App\Controller\RegisterController::index

contact:
  path: /contact
  controller: App\Controller\ContactController::index

reviews:
  path: /reviews
  controller: App\Controller\ReviewsController::index

reviews_create:
  path: /reviews/create
  controller: App\Controller\ReviewsController::create

login_auth:
  path: /login/auth
  controller: App\Controller\LoginController::auth

register_create:
  path: /register/create
  controller: App\Controller\RegisterController::create

products:
  path: /products
  controller: App\Controller\ProductController::index
